### PR TITLE
🍱 Add high res template image

### LINKED ISSUE #9: Fix tray icon diplay on macOS
- the resolution does not match my high-res display and
- the icon size does not match the other icons, which have a bit more padding

Screenshot showing the previously described issues

As you can see, it looks out of place next to the other icons.

### PR DESCRIPTION
**Pull request by Importantus**
I created a new template image with a higher resolution (256px) with the icon having an actual size of 186px to feel the same weight as the system menu bar items. I'm not sure whether it's allowed to use images above 22px. Maybe @nightsplinter or @hoppjan could test it...

### CODE REVIEW

**Comment by hoppjan** [comment]
I tested it and the tray icon does not seem to appear at all.
_Unless_ I switch desktops, in which case I can see a completely oversized icon!
Screenshot showing a tray icon the size many times any other, with cut off top an bottom

*Very* high-res! 🎉 😆

**Comment by Importantus** [comment]
Okay, new attempt. Now the image is actually 22px in size. Can you try it again?

**Comment by hoppjan** [comment]
Nope. But better
Tray icon with a low resolution next to properly working icons

**Comment by Importantus** [comment]
Now I tried adding different file sizes as it is described here: https://www.electronjs.org/docs/latest/api/native-image . Can you try it again? :)

**Comment by hoppjan** [comment]
Beautiful!

**Review by hoppjan — APPROVED** [review]
Love it ^^

**Pull request merged**
